"""
Clean database to keep ONLY real signed-up users
Removes all mock/test data generated by scripts
"""
from database import SessionLocal, engine
import models

def clean_database():
    db = SessionLocal()
    
    print("🧹 Cleaning FairFlow Database...")
    print("=" * 50)
    
    # List of real signed-up user emails (update this list with actual signup emails)
    # These are users who signed up through the /signup/driver or /signup/admin endpoints
    real_users = ["ridumika2501@gmail.com", "shakthi@example.com"]  # Add your actual signup emails here
    
    # Get all users
    all_users = db.query(models.User).all()
    print(f"\n📊 Total users in database: {len(all_users)}")
    
    # Identify mock/test users
    mock_users = []
    for user in all_users:
        if user.email not in real_users:
            mock_users.append(user)
    
    print(f"🗑️  Mock/test users to remove: {len(mock_users)}")
    
    # Show which users will be removed
    if mock_users:
        print("\n📋 Users that will be DELETED:")
        for user in mock_users:
            print(f"   - {user.name} ({user.email}) - ID: {user.id}")
    
    # Ask for confirmation
    confirm = input("\n⚠️  Proceed with deletion? (yes/no): ").strip().lower()
    
    if confirm != "yes":
        print("❌ Cleanup canceled.")
        db.close()
        return
    
    # Delete related data first (due to foreign key constraints)
    deleted_stats = 0
    deleted_routes = 0
    deleted_history = 0
    
    for user in mock_users:
        # Delete driver stats
        stats = db.query(models.DriverStats).filter(models.DriverStats.user_id == user.id).all()
        for s in stats:
            db.delete(s)
            deleted_stats += 1
        
        # Delete routes
        routes = db.query(models.Route).filter(models.Route.driver_id == user.id).all()
        for r in routes:
            db.delete(r)
            deleted_routes += 1
        
        # Delete fairness history
        history = db.query(models.FairnessHistory).filter(models.FairnessHistory.driver_id == user.id).all()
        for h in history:
            db.delete(h)
            deleted_history += 1
        
        # Delete user
        db.delete(user)
    
    # Commit all deletions
    db.commit()
    
    print(f"\n✅ Cleanup Complete!")
    print(f"   - Deleted {len(mock_users)} users")
    print(f"   - Deleted {deleted_stats} driver stats records")
    print(f"   - Deleted {deleted_routes} routes")
    print(f"   - Deleted {deleted_history} history records")
    
    # Show remaining users
    remaining = db.query(models.User).all()
    print(f"\n👥 Remaining users: {len(remaining)}")
    for user in remaining:
        print(f"   ✓ {user.name} ({user.email}) - {user.role}")
    
    db.close()

if __name__ == "__main__":
    clean_database()
